name: Docker Build and Publish to GHCR

on:
  push:
    branches:
      - main
      - dev
      - dev2

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Cache Docker layers
        uses: actions/cache@v4.0.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/chat-with-gpt:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Trigger Portainer Stack Update on main Branch
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}

      - name: Trigger Portainer Stack Update on dev Branch
        if: github.ref == 'refs/heads/dev'
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL_DEV }}

      - name: Trigger Portainer Stack Update on dev2 Branch
        if: github.ref == 'refs/heads/dev2'
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL_DEV2 }}

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ghcr.io/${{ github.repository_owner }}/chat-with-gpt:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
          dockerfile: ./Dockerfile
